//Auth 
export const USER_LOGIN_SUCCESS='USER_LOGIN_SUCCESS'
export const USER_LOGIN_START='USER_LOGIN_START'
export const USER_LOGIN_FAILED='USER_LOGIN_FAILED'

//Register 
export const USER_REGISTER_START='USER_REGISTER_START'
export const USER_REGISTER_SUCCESS='USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAILED='USER_REGISTER_FAILED'

//Change password
export const CHANGE_PASSWORD_START='CHANGE_PASSWORD_START'
export const CHANGE_PASSWORD_SUCCESS='CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_FAILED='CHANGE_PASSWORD_FAILED'